CREATE TABLE IF NOT EXISTS users (
  username VARCHAR(40) PRIMARY KEY NOT NULL,
  password VARCHAR(60) NOT NULL,
  token VARCHAR(50) NOT NULL,
  account_type VARCHAR(3) NOT NULL,
  activated TINYINT NOT NULL
);
